MAIL_SERVER = 'smtp.qq.com'
MAIL_POR = 465
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
MAIL_DEFAULT_SENDER = ''
MAIL_RECEIVER = ['']
SECURITY_PASSWORD_SALT = 'FdNCX23cP6t0qdCT'
RANDOM_SALT = 'ppLpBD1SG7ZYvrrI'
SECRET_KEY = 'dztQWBPGjI18bZSv'



